openapi: 3.0.0
info:
  title: revoteen
  version: '1.0'
  description: ''
servers:
  - url: 'http://dev.revoteen.com/api'
    description: development staging
paths:
  /users:
    post:
      summary: POST /users
      tags: []
      responses:
        '201':
          description: Created
      operationId: post-users
      description: creates a new user
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: firebase auth id token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                email:
                  type: string
                username:
                  type: string
                UID:
                  type: string
            examples:
              example-2:
                value:
                  displayName: string
                  email: string
                  username: string
                  UID: SE3IKvcD8dRjfiyI74uj9G0cY2o1
        description: ''
components:
  schemas: {}
  securitySchemes: {}
